apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# manifests are in the _manifests folder just to keep things clean
- _manifests/deployment.yaml
- _manifests/ingress.yaml
- _manifests/service.yaml

# this could maybe just be pointed to .env depending on how adam wants to develop
configMapGenerator:
- name: bton-env
  env: .env-kubernetes

generatorOptions:
# labels to add to all generated resources
  labels:
    kustomize.generated.resources: bton
    app.kubernetes.io/name: bton
  # annotations to add to all generated resources
  annotations:
    kustomize.generated.resource: bton

  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  # This also allows the configmap to be deleted during a purge instead of remaining behind!
  disableNameSuffixHash: true